// Запрос «LOAD_Сводная»
// Назначение: построить таблицу для листа «LOAD»: уникальные пары «Короткое наименование ТБ» + «ГОСБ»,
// столбцы по типам отбора; в ячейках — КМ (сокращённое ФИО), удовлетворяющие фильтру:
//   ВЫБРАН = 1, совпадение ТБ и ГОСБ, в «ОТБОР» встречается название типа (без учёта регистра).
// Формат ФИО в ячейке: «Фамилия И.О.» с переносом строки между людьми (#(lf) → Alt+Enter в Excel).
//
// Источник: запрос «Отбор_На_BASE» (должен успешно выполняться).

let
    ИсходнаяТаблица = #"Отбор_На_BASE",

    // Список типов отбора — порядок столбков на листе «LOAD» (после ТБ и ГОСБ)
    ТипыОтбора =
        {
            "ЗОЛОТО",
            "MAX BADGES",
            "СТРАЙК РОСТ ОД",
            "СТРАЙК ЭФФЕКТИВНОСТЬ",
            "ЭФФЕКТИВЕН",
            "РОСТ ОД",
            ">50% ТЕМП ОД",
            ">50% ТЕМП ОД ТБ"
        },

    // --- Вспомогательная функция: полное ФИО → «Фамилия И.О.» ---
    // Правило: первый токен — фамилия; по каждому следующему слову — первая буква и точка, без пробела между инициалами.
    fnСократитьФИО = (полное as nullable text) as text =>
        let
            Сырой = if полное = null then "" else Text.Trim(Text.From(полное)),
            Части =
                if Сырой = "" then
                    {}
                else
                    Text.Split(Сырой, " "),
            ЧастиБезПустых = List.Select(Части, each Text.Trim(_) <> ""),
            РезультатФио =
                if List.Count(ЧастиБезПустых) = 0 then
                    ""
                else if List.Count(ЧастиБезПустых) = 1 then
                    ЧастиБезПустых{0}
                else
                    let
                        Фамилия = ЧастиБезПустых{0},
                        Остальные = List.Skip(ЧастиБезПустых, 1),
                        Инициалы =
                            List.Transform(
                                Остальные,
                                each Text.Upper(Text.Start(_, 1)) & "."
                            ),
                        СклейкаИнициалов = Text.Combine(Инициалы, "")
                    in
                        Фамилия & " " & СклейкаИнициалов
        in
            РезультатФио,

    // --- Проверка: отбор включён (1 или «1») ---
    fnВыбранДа = (значение as any) as logical =>
        let
            КакТекст = try Text.Trim(Text.From(значение)) otherwise "",
            КакЧисло = try Number.From(значение) otherwise null
        in
            (КакЧисло = 1) or (КакТекст = "1"),

    // --- Подстрока в ОТБОР без учёта регистра (совместимость с Excel 2016) ---
    fnОтборСодержитТип = (текстОтбора as nullable text, тип as text) as logical =>
        let
            Т = if текстОтбора = null then "" else Text.From(текстОтбора)
        in
            Text.Contains(Text.Upper(Т), Text.Upper(тип)),

    // Строки, по которым считаем КМ
    СтрокиДляАнализа =
        Table.SelectRows(
            ИсходнаяТаблица,
            each fnВыбранДа([ВЫБРАН])
        ),

    // Уникальные пары ТБ + ГОСБ из всего файла (как в ТЗ), не только из ВЫБРАН=1
    УникальныеПары =
        Table.Distinct(
            Table.SelectColumns(
                ИсходнаяТаблица,
                {"Короткое наименование ТБ", "ГОСБ"}
            )
        ),

    // Для каждой пары и каждого типа собираем список КМ
    fnСобратьКмДляЯчейки =
        (тб as any, госб as any, тип as text) as text =>
            let
                Отфильтровано =
                    Table.SelectRows(
                        СтрокиДляАнализа,
                        each
                            ([Короткое наименование ТБ] = тб)
                            and ([ГОСБ] = госб)
                            and fnОтборСодержитТип([ОТБОР], тип)
                    ),
                СписокКм = Table.Column(Отфильтровано, "КМ"),
                Сокращённые = List.Transform(СписокКм, each fnСократитьФИО(_)),
                БезПустых = List.Select(Сокращённые, each _ <> ""),
                Уникальные = List.Distinct(БезПустых),
                ТекстЯчейки = Text.Combine(Уникальные, "#(lf)")
            in
                ТекстЯчейки,

    // Добавляем столбец по каждому типу отбора
    СТиповымиКолонками =
        List.Accumulate(
            ТипыОтбора,
            УникальныеПары,
            (состояние as table, тип as text) as table =>
                Table.AddColumn(
                    состояние,
                    тип,
                    each
                        fnСобратьКмДляЯчейки(
                            [Короткое наименование ТБ],
                            [ГОСБ],
                            тип
                        ),
                    type text
                )
        ),

    Результат = СТиповымиКолонками
in
    Результат
