// ЕДИНЫЙ ЗАПРОС ДЛЯ EXCEL POWER QUERY (Excel 2016, русская локаль)
// Что делает:
// 1) Загружает CSV "Отбор.csv" из папки текущей книги (через именованную область "КаталогРабочейКниги").
// 2) Может вернуть либо исходную таблицу BASE, либо итоговую сводную LOAD.
//
// Как использовать:
// - В книге Excel создайте именованную область "КаталогРабочейКниги" (1 ячейка) с формулой:
//   =ЛЕВСИМВ(ЯЧЕЙКА("имяфайла";A1);ПОИСК("[";ЯЧЕЙКА("имяфайла";A1))-1)
// - В шаге "РежимВывода" поставьте:
//   "BASE"  -> чтобы вернуть исходные данные CSV
//   "LOAD"  -> чтобы вернуть итоговую таблицу по типам отбора
//
// Примечание:
// Один запрос Power Query возвращает только один итоговый набор данных.
// Для одновременной загрузки на два листа (BASE и LOAD) обычно делают 2 запроса-ссылки.

let
    // ====================== НАСТРОЙКА ВЫВОДА ======================
    РежимВывода = "LOAD",

    // ====================== ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ ======================
    fnСократитьФИО = (полное as nullable text) as text =>
        let
            СыройТекст = if полное = null then "" else Text.Trim(Text.From(полное)),
            ЧастиФио =
                if СыройТекст = "" then
                    {}
                else
                    Text.Split(СыройТекст, " "),
            ЧастиБезПустых = List.Select(ЧастиФио, each Text.Trim(_) <> ""),
            РезультатФио =
                if List.Count(ЧастиБезПустых) = 0 then
                    ""
                else if List.Count(ЧастиБезПустых) = 1 then
                    ЧастиБезПустых{0}
                else
                    let
                        Фамилия = ЧастиБезПустых{0},
                        ОстальныеСлова = List.Skip(ЧастиБезПустых, 1),
                        Инициалы = List.Transform(ОстальныеСлова, each Text.Upper(Text.Start(_, 1)) & "."),
                        ИнициалыСклеены = Text.Combine(Инициалы, "")
                    in
                        Фамилия & " " & ИнициалыСклеены
        in
            РезультатФио,

    fnВыбранДа = (значение as any) as logical =>
        let
            КакТекст = try Text.Trim(Text.From(значение)) otherwise "",
            КакЧисло = try Number.From(значение) otherwise null
        in
            (КакЧисло = 1) or (КакТекст = "1"),

    fnОтборСодержитТип = (текстОтбора as nullable text, типОтбора as text) as logical =>
        let
            БезNull = if текстОтбора = null then "" else Text.From(текстОтбора)
        in
            Text.Contains(Text.Upper(БезNull), Text.Upper(типОтбора)),

    // ====================== ШАГ 1: ПУТЬ К КАТАЛОГУ КНИГИ ======================
    Шаг01_ТаблицаПути = Excel.CurrentWorkbook(){[Name = "КаталогРабочейКниги"]}[Content],
    Шаг02_ИмяПервогоСтолбца = Table.ColumnNames(Шаг01_ТаблицаПути){0},
    Шаг03_ПутьСырой = Record.Field(Шаг01_ТаблицаПути{0}, Шаг02_ИмяПервогоСтолбца),
    Шаг04_ПутьТекст = Text.Trim(Text.From(Шаг03_ПутьСырой)),
    Шаг05_ПутьСоСлэшем =
        if Text.EndsWith(Шаг04_ПутьТекст, "\") then
            Шаг04_ПутьТекст
        else
            Шаг04_ПутьТекст & "\",

    // ====================== ШАГ 2: ЧТЕНИЕ CSV ======================
    Шаг06_ИмяФайла = "Отбор.csv",
    Шаг07_ПолныйПуть = Шаг05_ПутьСоСлэшем & Шаг06_ИмяФайла,
    Шаг08_БинарныеДанные = File.Contents(Шаг07_ПолныйПуть),
    Шаг09_ТекстФайла = Text.FromBinary(Шаг08_БинарныеДанные, 1251),
    Шаг10_ПозицияПереноса = Text.PositionOfAny(Шаг09_ТекстФайла, {"#(cr)", "#(lf)"}),
    Шаг11_ПерваяСтрока =
        if Шаг10_ПозицияПереноса = -1 then
            Шаг09_ТекстФайла
        else
            Text.Start(Шаг09_ТекстФайла, Шаг10_ПозицияПереноса),
    Шаг12_КолвоТочекСЗапятой = Text.Length(Шаг11_ПерваяСтрока) - Text.Length(Text.Replace(Шаг11_ПерваяСтрока, ";", "")),
    Шаг13_КолвоЗапятых = Text.Length(Шаг11_ПерваяСтрока) - Text.Length(Text.Replace(Шаг11_ПерваяСтрока, ",", "")),
    Шаг14_Разделитель =
        if Шаг12_КолвоТочекСЗапятой >= Шаг13_КолвоЗапятых then
            ";"
        else
            ",",
    Шаг15_CsvТаблица = Csv.Document(Шаг08_БинарныеДанные, [Delimiter = Шаг14_Разделитель, Encoding = 1251]),
    Шаг16_БазаСЗаголовками = Table.PromoteHeaders(Шаг15_CsvТаблица, [PromoteAllScalars = true]),
    Шаг17_ИменаКолонок = Table.ColumnNames(Шаг16_БазаСЗаголовками),
    Шаг18_БазаСТипами =
        if List.Contains(Шаг17_ИменаКолонок, "ВЫБРАН") then
            Table.TransformColumnTypes(Шаг16_БазаСЗаголовками, {{"ВЫБРАН", type number}}, "ru-RU")
        else
            Шаг16_БазаСЗаголовками,

    // ====================== ШАГ 3: СБОРКА LOAD ======================
    Шаг19_ТипыОтбора =
        {
            "ЗОЛОТО",
            "MAX BADGES",
            "СТРАЙК РОСТ ОД",
            "СТРАЙК ЭФФЕКТИВНОСТЬ",
            "ЭФФЕКТИВЕН",
            "РОСТ ОД",
            ">50% ТЕМП ОД",
            ">50% ТЕМП ОД ТБ"
        },
    Шаг20_ТолькоВыбранные = Table.SelectRows(Шаг18_БазаСТипами, each fnВыбранДа([ВЫБРАН])),
    Шаг21_УникальныеПарыТБГОСБ =
        Table.Distinct(
            Table.SelectColumns(
                Шаг18_БазаСТипами,
                {"Короткое наименование ТБ", "ГОСБ"}
            )
        ),
    fnСобратьКмДляЯчейки = (тб as any, госб as any, тип as text) as text =>
        let
            Отфильтровано =
                Table.SelectRows(
                    Шаг20_ТолькоВыбранные,
                    each
                        ([Короткое наименование ТБ] = тб)
                        and ([ГОСБ] = госб)
                        and fnОтборСодержитТип([ОТБОР], тип)
                ),
            СписокКм = Table.Column(Отфильтровано, "КМ"),
            СокращенныеФио = List.Transform(СписокКм, each fnСократитьФИО(_)),
            БезПустых = List.Select(СокращенныеФио, each _ <> ""),
            Уникальные = List.Distinct(БезПустых),
            Склейка = Text.Combine(Уникальные, "#(lf)")
        in
            Склейка,
    Шаг22_LOADСКолонками =
        List.Accumulate(
            Шаг19_ТипыОтбора,
            Шаг21_УникальныеПарыТБГОСБ,
            (состояние as table, тип as text) as table =>
                Table.AddColumn(
                    состояние,
                    тип,
                    each fnСобратьКмДляЯчейки([Короткое наименование ТБ], [ГОСБ], тип),
                    type text
                )
        ),

    // ====================== ШАГ 4: ВЫБОР ИТОГА ======================
    Шаг23_Итог =
        if Text.Upper(РежимВывода) = "BASE" then
            Шаг18_БазаСТипами
        else
            Шаг22_LOADСКолонками
in
    Шаг23_Итог
