// Запрос «Отбор_На_BASE»
// Назначение: загрузить «Отбор.csv» из той же папке, что и книга Excel, с кодировкой Windows-1251.
// Результат: таблица для выгрузки на лист «BASE» (через «Закрыть и загрузить в…» → таблица на лист).
//
// Зависимости: запрос «Настройка_ПутьККаталогу» (именованная область «КаталогРабочейКниги» в книге).

let
    Папка = #"Настройка_ПутьККаталогу",
    ИмяФайла = "Отбор.csv",
    ПолныйПуть = Папка & ИмяФайла,
    ДвоичныеДанные = File.Contents(ПолныйПуть),
    // Автоопределение разделителя: сравниваем количество «;» и «,» в первой строке
    // Важно: кодировку задаём через Text.FromBinary, чтобы не попасть в параметр QuoteStyle.
    ТекстФайла = Text.FromBinary(ДвоичныеДанные, 1251),
    ПозицияПереноса = Text.PositionOfAny(ТекстФайла, {"#(cr)", "#(lf)"}),
    ПерваяСтрока =
        if ПозицияПереноса = -1 then
            ТекстФайла
        else
            Text.Start(ТекстФайла, ПозицияПереноса),
    КолвоТочекСЗапятой =
        Text.Length(ПерваяСтрока) - Text.Length(Text.Replace(ПерваяСтрока, ";", "")),
    КолвоЗапятых =
        Text.Length(ПерваяСтрока) - Text.Length(Text.Replace(ПерваяСтрока, ",", "")),
    Разделитель =
        if КолвоТочекСЗапятой >= КолвоЗапятых then
            ";"
        else
            ",",
    // QuoteStyle не используем — лучшая совместимость с Excel 2016
    ДокументCsv =
        Csv.Document(
            ДвоичныеДанные,
            [Delimiter = Разделитель, Encoding = 1251]
        ),
    ПерваяСтрокаЗаголовки = Table.PromoteHeaders(ДокументCsv, [PromoteAllScalars = true]),
    ИменаКолонок = Table.ColumnNames(ПерваяСтрокаЗаголовки),
    // Приведение типа «ВЫБРАН» к числу, если столбец есть (в исходнике бывает текст «1»)
    ТипыСтолбцов =
        if List.Contains(ИменаКолонок, "ВЫБРАН") then
            Table.TransformColumnTypes(
                ПерваяСтрокаЗаголовки,
                {{"ВЫБРАН", type number}},
                "ru-RU"
            )
        else
            ПерваяСтрокаЗаголовки,
    Результат = ТипыСтолбцов
in
    Результат
